// src/components/VatRateDisplay.tsx
import type { VatRate } from 'nav-osa-types';
import { countDecimals, esc, type TFn, type NFn } from './utils.js';

interface Props {
    vatRate: VatRate;
    t: TFn;
    nf: NFn;
}

export function VatRateDisplay({ vatRate, t, nf }: Props): string {
    let label = '';

    if (vatRate.vatPercentage) {
        label = `${nf(vatRate.vatPercentage, countDecimals(vatRate.vatPercentage))}%`;
    } else if (vatRate.vatContent) {
        label = `${nf(vatRate.vatContent, countDecimals(vatRate.vatContent))}%`;
    } else if (vatRate.vatExemption) {
        label = `${t('vatExemption') || t('vatExempt')}: ${vatRate.vatExemption.case}`;
    } else if (vatRate.vatOutOfScope) {
        label = `${t('vatOutOfScope')}: ${vatRate.vatOutOfScope.case}`;
    } else if (vatRate.vatDomesticReverseCharge) {
        label = t('vatDomesticReverseCharge');
    } else if (vatRate.marginSchemeIndicator) {
        label = `${t('marginScheme')}: ${t(vatRate.marginSchemeIndicator)}`;
    } else if (vatRate.noVatCharge) {
        label = t('noVatCharge');
    } else {
        label = t('vatExempt');
    }

    return label;
}

/** Small note with the exemption / out-of-scope reason, if any (for wide cells, e.g. summary tables) */
export function VatRateReasonNote({ vatRate }: { vatRate: VatRate }): string {
    if (vatRate.vatExemption?.reason) {
        return `<br /><small>${esc(vatRate.vatExemption.reason)}</small>`;
    }
    if (vatRate.vatOutOfScope?.reason) {
        return `<br /><small>${esc(vatRate.vatOutOfScope.reason)}</small>`;
    }
    return '';
}

// src/components/VatRateDisplay.svelte
<script lang="ts">
    import type { VatRate } from "../osaTypes/dataTypes.js";

    export let vatRate: VatRate;
    export let t: (key: string) => string;
    export let nf: (val: any, decimals?: number) => string;
</script>

{#if vatRate.vatPercentage}
    {nf(vatRate.vatPercentage * 100)}%
{:else if vatRate.vatContent}
    {nf(vatRate.vatContent * 100)}%
{:else if vatRate.vatExemption}
    {t("vatExemption") || t("vatExempt")}: {vatRate.vatExemption.case}
{:else if vatRate.vatOutOfScope}
    {t("vatOutOfScope")}: {vatRate.vatOutOfScope.case}
{:else if vatRate.vatDomesticReverseCharge}
    {t("vatDomesticReverseCharge")}
{:else if vatRate.marginSchemeIndicator}
    {t("marginScheme")}: {t(vatRate.marginSchemeIndicator)}
{:else if vatRate.noVatCharge}
    {t("noVatCharge")}
{:else}
    {t("vatExempt")}
{/if}

{#if vatRate.vatAmountMismatch}
    <br /><small class="vat-mismatch-note">
        ⚠️ {t("vatAmountMismatch")}: {nf(
            vatRate.vatAmountMismatch.vatRate * 100,
        )}% ({vatRate.vatAmountMismatch.case})
    </small>
{/if}
